### ISSUE TITLE
import graphlab error

### ISSUE THREAD

**Issue by arun0297** [dato-code/how-to#41]
![image](https://cloud.githubusercontent.com/assets/18597124/23338886/0dc58a68-fc3c-11e6-8240-e15cc4b040b7.png)

I have installed graphlab using pip install graphlab
anaconda & miniconda are also installed in my ubuntu 16.10

How to fix this error?

**Comment by utkarshrai** [comment]
Hi Arun. I hope you have resolved the issue by now.
If you haven't, you need to verify your license with graphlab.

##Install your licensed copy of GraphLab Create
pip install --upgrade --no-cache-dir https://get.graphlab.com/GraphLab-Create/2.1/your registered email address here/your product key here/GraphLab-Create-License.tar.gz
You need to register for one.

**Comment by utkarshrai** [comment]
https://github.com/utkarshrai/TweetAnalysis/blob/master/graphlab/Setting_Up_graphlab_on_Linux.md
I just uploaded some screenshots.
